name: actions-check

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install deps
        run: pip install requests

      - name: run check
        run: python monitor.py
