name: xianyu-monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install requests
        run: pip install requests

      - name: run script
        run: python monitor.py
